{% set name = "napari-sam" %}
{% set version = "0.4.11" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/napari-sam-{{ version }}.tar.gz
  sha256: 0d3d0dd28a7c42c42450ba3241a0902e7f4c4e400a06ba4226a3f27d28253ade

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - python >=3.8
  run:
    - napari
    - napari-nifti
    - numpy
    - magicgui
    - python >=3.8
    - qtpy
    - segment-anything
    - tqdm
    - vispy

test:
  imports:
    - napari_sam
  commands:
    - pip list
    - pip check
  requires:
    - pip

about:
  home: https://github.com/MIC-DKFZ/napari-sam
  summary: Segment anything with Meta AI's new SAM model!
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - goanpeca
    - jaimergp
    - Karol-G
