{% set name = "napari-sam" %}
{% set version = "0.4.12" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/napari-sam-{{ version }}.tar.gz
  sha256: dada7b279a74bc4d47dca8494aeb36f367f52830dab89307d39f2539303b615e

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - python >=3.8
  run:
    - napari
    - napari-nifti
    - numpy
    - magicgui
    - python >=3.8
    - pytorch >=1.7
    - qtpy
    - segment-anything
    - superqt
    - torchvision >=0.8
    - tqdm
    - vispy

test:
  imports:
    - napari_sam
  commands:
    - pip list
    - pip check
  requires:
    - pip
    - pyqt

about:
  home: https://github.com/MIC-DKFZ/napari-sam
  summary: Segment anything with Meta AI's new SAM model!
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - goanpeca
    - jaimergp
    - Karol-G
